### ISSUE TITLE
Update action to use Node.js 20

### ISSUE THREAD

**Issue by timaadland** [evryfs/notify-slack-action#7]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: evryfs/notify-slack-action@js-v1.0.0. For more information see: [github-actions-transitioning-from-node-16-to-node-20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.)

**Comment by rainui28** [comment]
https://github.com/evryfs/notify-slack-action/releases/tag/js-v2.0.0

<blockquote><img src="https://opengraph.githubassets.com/f094ed5c958b6e2edad7ee3bf997c3194d6554fda4ff8d6fed18bb79c7d889e6/evryfs/notify-slack-action/releases/tag/js-v2.0.0" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/evryfs/notify-slack-action/releases/tag/js-v2.0.0">Release js-v2.0.0 · evryfs/notify-slack-action</a></strong></div><div>new: bump node:20

What's Changed

Change usage part in README to reflect current state by @Otterian in #1
Bump Action to node20 by @Otterian in #9

New Contributors

@Otterian made their first con...</div></blockquote>
